package org.example.notification.shared.api;

public enum ApiErrorCode {
  VALIDATION_FAILED,
  MALFORMED_REQUEST,
  ACCESS_DENIED,
  INVALID_CREDENTIALS,
  RESOURCE_NOT_FOUND,
  CONFLICT,
  IDEMPOTENCY_CONFLICT,
  TEMPLATE_VARIABLE_MISSING,
  CHANNEL_DISABLED,
  INVALID_STATE
}
